boot:
  dynamicDS:
    uosp40100:
        defaultDS: true
        url: jdbc:mysql://twp.nevermore.tech:43306/dfs?useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
     uospTWP:
        url: jdbc:oracle:thin:@twp.nevermore.tech:49161/XE
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: uosp
        password: 123456