#spring:
#    mail:
#        default-encoding: UTF-8
#        host: smtp.163.com
#        username: shadowsstt@163.com
#        # 授权码
#        password: twpemail123456
#        properties:
#            mail:
#              smtp:
#                timeout: 25000
#                auth: true
#                starttls:
#                    enable: true
#                    required: true